services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "ambitiousdb-dev-environment"
    container_name: ambitious-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - db_data:/ambitiousdb/data
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    db_data:
      external: true

